services:
  nginx:
    build:
      context: extenginx
      additional_contexts:
        - NGINX_SNIPPET_SOURCE=./nginx_snippets
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HOSTNAME: kdlp.underground.software
    volumes:
      - ./ssl:/etc/ssl/nginx:ro,z
      - ./kdlp.underground.software:/var/www/html:ro,z
    ports:
      - 80:80
      - 443:443
      - 465:465
      - 995:995
  orbit:
    build:
      context: orbit
      dockerfile: Containerfile
      target: orbit
    volumes:
      - .:/var/git/syzygy:ro,z
      - ./cgitrc.repos:/etc/cgitrc.repos:ro,z
      - ./kdlp.underground.software:/orbit/docs:ro,z
    ports:
      - 9098:9098
  tcp_server:
    build:
      context: tcp_server
      dockerfile: Containerfile
      target: tcp_server
  smtp:
    build:
      context: smtp
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_CONTAINER=container-image://localhost/syzygy_tcp_server:latest
      target: smtp
      args:
        hostname: kdlp.underground.software
    volumes:
      - ./email:/mnt/email_data:z
    ports:
      - 11465:465
  pop:
    build:
      context: pop
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_CONTAINER=container-image://localhost/syzygy_tcp_server:latest
      target: pop
    volumes:
      - ./email/mail:/mnt/mail:ro,z
    ports:
      - 11995:995
