services:
  nginx:
    build:
      context: extenginx
      additional_contexts:
        - NGINX_SNIPPET_SOURCE=./nginx_snippets
      dockerfile: Containerfile
      target: nginx
      args:
        NGINX_HTTP_PORT: 1080
        NGINX_HTTPS_PORT: 1443
        NGINX_SMTPS_PORT: 1465
        NGINX_POP3S_PORT: 1995
        NGINX_RUNTIME_SNIPPETS: 1
    security_opt:
      - label:disable
    volumes:
      - ./ssl:/etc/ssl/nginx:ro,z
      - ./nginx_snippets:/etc/nginx/include.d:ro,z
      - ./kdlp.underground.software:/var/www/html:ro,z
    ports:
      - 1080:1080
      - 1443:1443
      - 1465:1465
      - 1995:1995
  orbit:
    build:
      context: orbit
      dockerfile: Containerfile
      target: orbit
    security_opt:
      - label:disable
    volumes:
      - ./.git:/var/git/syzygy:ro,z
      - ./.git/modules/orbit:/var/git/orbit:ro,z
      - ./.git/modules/tcp_server:/var/git/tcp_server:ro,z
      - ./.git/modules/pop:/var/git/pop:ro,z
      - ./.git/modules/smtp:/var/git/smtp:ro,z
      - ./.git/modules/extenginx:/var/git/extenginx:ro,z
      - ./.git/modules/kdlp.underground.software:/var/git/kdlp.underground.software:ro,z
      - ./kdlp.underground.software:/orbit/docs:ro,z
    ports:
      - 9098:9098
  tcp_server:
    build:
      context: tcp_server
      dockerfile: Containerfile
      target: tcp_server
  smtp:
    build:
      context: smtp
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_CONTAINER=container-image://localhost/syzygy_tcp_server:latest
      target: smtp
      args:
        hostname: localhost
    volumes:
      - ./email:/mnt/email_data:z
    ports:
      - 11465:465
  pop:
    build:
      context: pop
      dockerfile: Containerfile
      additional_contexts:
        - TCP_SERVER_CONTAINER=container-image://localhost/syzygy_tcp_server:latest
      target: pop
    volumes:
      - ./email/mail:/mnt/mail:ro,z
    ports:
      - 11995:995
  submatrix:
    build:
      context: submatrix
      dockerfile: Containerfile
      target: submatrix
    volumes:
      - ./ssl:/ssl
    ports:
      - 8448:8448
