FROM alpine:3.19 AS build
RUN apk update && apk upgrade && apk add clang make
ARG hostname
RUN test -n "$hostname" || (echo 'hostname is not set' >&2; exit 1)
COPY ./smtp /smtp
RUN make -C /smtp CC='clang -static' SRVNAME=$hostname

FROM scratch as smtp
COPY ./tcp_server/tcp_server /tcp_server
COPY --from=build /smtp/smtp /smtp
ENTRYPOINT ["/tcp_server", "-p", "465", "/smtp", "smtp", "/email"]
