services:
  nginx:
    build:
      dockerfile: Containerfile.extenginx
      target: nginx
      args:
        NGINX_HOSTNAME: ${HOSTNAME}
        NGINX_HTTP_PORT: ${NGINX_HTTP_PORT}
        NGINX_HTTPS_PORT: ${NGINX_HTTPS_PORT}
        NGINX_SMTPS_PORT: ${NGINX_SMTPS_PORT}
        NGINX_POP3S_PORT: ${NGINX_POP3S_PORT}
    volumes:
      - ./volumes/ssl:/etc/ssl/nginx:ro,z
      - ./nginx_snippets:/etc/nginx/include.d:ro,z
      - ./kdlp.underground.software:/var/www/html:ro,z
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
      - ${NGINX_SMTPS_PORT}:465
      - ${NGINX_POP3S_PORT}:995
  orbit:
    build:
      context: orbit
      dockerfile: Containerfile
      target: orbit
    volumes:
      - ./.git:/var/git/syzygy:ro,z
      - ./.git/modules/orbit:/var/git/orbit:ro,z
      - ./.git/modules/tcp_server:/var/git/tcp_server:ro,z
      - ./.git/modules/pop:/var/git/pop:ro,z
      - ./.git/modules/smtp:/var/git/smtp:ro,z
      - ./.git/modules/extenginx:/var/git/extenginx:ro,z
      - ./.git/modules/kdlp.underground.software:/var/git/kdlp.underground.software:ro,z
      - ./kdlp.underground.software:/orbit/docs:ro,z
  smtp:
    build:
      dockerfile: Containerfile.smtp
      target: smtp
      args:
        hostname: ${HOSTNAME}
    volumes:
      - ./volumes/email:/email:z
    ports:
      - 11465:465
  pop3:
    build:
      dockerfile: Containerfile.pop3
      target: pop3
    volumes:
      - ./volumes/email/mail:/mail:ro,z
    ports:
      - 11995:995
